apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codefresh
patches:
- patch: "\n\t\t\top: add\n\t\t\t\tpath: /spec/template/spec/containers/0/env\n\t\t\t\tvalue:\n\t\t\t\t\t-
    name: BASE_HREF\n\t\t\t\t\t\tvalue: /workflows/\n\t\t"
  target:
    group: ~G
    kind: ~K
    name: argo-server
    version: ~V
resources:
- ../../base
- ingress.yaml
