apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codefresh
resources:
- ../../base

images:
 - name: docker.io/argoproj/argocli
   newName: docker.io/argoproj/argocli
   newTag: blahblah
